#!/usr/bin/env bash
# One entry point for both desktops. Git Bash on Windows and bash on Linux
# run this same file; only the name of make differs between them.
#
# The stamp is written BEFORE make runs, so the binary carries the moment it
# was compiled rather than the moment before. The cost is that main.c
# recompiles on every invocation -- build_timestamp.inc is always newer than
# the object it feeds. That is the intended trade, not an oversight.
set -euo pipefail

cd "$(dirname "$0")"

case "$(uname -s)" in
	MINGW*|MSYS*|CYGWIN*) MAKE=mingw32-make ;;
	*)                    MAKE=make ;;
esac

command -v "$MAKE" >/dev/null 2>&1 || {
	echo "make.sh: $MAKE is not on PATH" >&2
	exit 1
}

# ISO 8601 field order, but a space for the T and the zone spelled out:
# a human reads "UTC" faster than a trailing Z, and this string is read by
# people, not parsed. Not ISO 8601 proper -- deliberately.
STAMP="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"

cat > build_timestamp.inc <<EOF
// Generated by make.sh on every build. Not in git -- a clone has no such
// file until it is built, and main.h says "unknown" until then.
//
// Unlike milestone_iteration.inc beside it, nothing here is written by hand.
#define DBJ_THE_GAME_BUILD_TIMESTAMP "$STAMP"
EOF

exec "$MAKE" "$@"
